apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despachos
  namespace: innovatech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-despachos
  template:
    metadata:
      labels:
        app: backend-despachos
    spec:
      containers:
      - name: despachos
        image: ECR_REPO_BACK_DESPACHOS_PLACEHOLDER
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: despachos-service
  namespace: innovatech
spec:
  selector:
    app: backend-despachos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: despachos-hpa
  namespace: innovatech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-despachos
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50