apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  namespace: innovatech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
      - name: ventas
        image: ECR_REPO_BACK_VENTAS_PLACEHOLDER
        env:
        - name: DB_ENDPOINT
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: DB_PASSWORD
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "384Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /api/v1/ventas
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/ventas
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: ventas-service
  namespace: innovatech
spec:
  type: ClusterIP
  selector:
    app: backend-ventas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ventas-hpa
  namespace: innovatech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-ventas
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50