name: CI/CD Tienda Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 979842939605.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: tienda-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
                       -t $ECR_REGISTRY/$ECR_REPOSITORY:run-${{ github.run_number }} \
                       -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY

      - name: Deploy to EC2 via SSM
        working-directory: .
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_FRONTEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker pull ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest",
              "docker stop tienda-frontend || true",
              "docker rm tienda-frontend || true",
              "docker run -d --name tienda-frontend -p 80:80 ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest"
            ]' \
            --region ${{ secrets.AWS_REGION }}