name: CI/CD Front Despacho

on:
  push:
    branches: [ "main" ]
    paths:
      - 'front_despacho/**' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front_despacho 

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push to ECR
        env:
          ECR_REPOSITORY_URI: ${{ secrets.ECR_REPO_FRONT }}
        run: |
          docker build -t $ECR_REPOSITORY_URI:latest .
          docker push $ECR_REPOSITORY_URI:latest

      - name: Configurar kubectl
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name devopseks
      
      - name: Deploy a EKS
        run: |
          kubectl apply -f k8s/namespace.yaml
          sed -i "s|image: .*|image: ${{ secrets.ECR_REPO_FRONT }}:latest|g" k8s/front.yaml
          kubectl apply -f k8s/front.yaml